### ISSUE TITLE
Implement Python Execution Feature

### ISSUE THREAD

**Issue by ebresie** [ebresie/python4nb#4]
Presently as of 0.1, there is no ability to run a Python script.

This is issue will implement run functionality within the IDE.

**Comment by ebresie** [comment]
WIth installed nbm, and attempting to run, get following when attempting to run

java.lang.NullPointerException: Cannot invoke "org.openide.filesystems.FileObject.getParent()" because "script" is null
	at org.apache.netbeans.modules.python4nb.ui.actions.RunCommand.invokeAction(RunCommand.java:88)
	at org.apache.netbeans.modules.python4nb.project.PythonActionProvider$1.run(PythonActionProvider.java:99)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

**Comment by ebresie** [comment]
In code recently checked in (this check-in may have been premature but was done to avoid losing in work code), able to execute code once a default python platform has been selected, the main project file has been selected.  More cleaned up version of this will likely be in release 0.3

**Comment by ebresie** [comment]
Additional updates with recent commit.
